# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='example@me.com', max_length=254),
        ),
    ]
