# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keijiban', '0004_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='subject',
            field=models.CharField(max_length=64, null=True, verbose_name='科目名'),
        ),
    ]
